const {chromium}=require('C:/Users/Firdaus/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{fs.mkdirSync('test-results',{recursive:true});const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
await page.goto('http://127.0.0.1:8096/ot.php');await page.waitForLoadState('networkidle');await page.screenshot({path:'test-results/desktop-empty.png',fullPage:true});
await page.locator('#month').fill('2099-06');await page.locator('#month').dispatchEvent('change');await page.locator('[data-view=profile]').first().click();await page.locator('[name=salary]').fill('4073.17');await page.locator('[data-view=records]').first().click();
// Invalid date and missing description must retain input, with a focused inline error.
await page.locator('#add').click();await page.locator('[name=date]').fill('2099-05-31');await page.locator('textarea[name=description]').fill('Ujian kiraan Excel');await page.locator('#entry-form [type=submit]').click();assert.match(await page.locator('#entry-error').innerText(),/bukan dalam/);assert.equal(await page.locator('textarea[name=description]').inputValue(),'Ujian kiraan Excel');assert.equal(await page.locator('#entries tr').count(),0);
await page.locator('[name=date]').fill('2099-06-01');await page.locator('textarea[name=description]').fill('');await page.locator('#entry-form [type=submit]').click();assert.match(await page.locator('#entry-error').innerText(),/keterangan/);
await page.locator('textarea[name=description]').fill('Ujian kiraan Excel');await page.locator('[name=deduction]').fill('2');await page.locator('#entry-form [type=submit]').click();assert.match(await page.locator('#entry-error').innerText(),/melebihi/);await page.locator('#close-editor').click();
for(const [hours,band]of [['3','Day'],['0.5','Night']]){await page.locator('#add').click();await page.locator('[name=hours]').fill(hours);await page.locator('[name=band]').selectOption(band);await page.locator('textarea[name=description]').fill('Ujian kiraan Excel');await page.locator('#entry-form [type=submit]').click();}
assert.match(await page.locator('#total').innerText(),/78\.08/);await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#save-status').textContent==='Disimpan pada komputer ini');await page.reload();await page.waitForLoadState('networkidle');await page.locator('#saved-month').selectOption('2099-06');assert.match(await page.locator('#total').innerText(),/78\.08/);assert.equal(await page.locator('#entries tr').count(),2);
await page.screenshot({path:'test-results/desktop-filled.png',fullPage:true});
// Salary does not erase rows when temporarily cleared.
await page.locator('[data-view=profile]').first().click();await page.locator('[name=salary]').fill('');await page.locator('#save').click();assert.match(await page.locator('#notice').innerText(),/gaji pokok/);assert.equal(await page.locator('#entries tr').count(),2);await page.locator('[name=salary]').fill('4073.17');await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'test-results/profile.png',fullPage:true});await page.locator('[data-view=records]').first().click();

await page.locator('[data-edit]').first().click();await page.locator('[name=hours]').fill('4');await page.locator('#entry-form [type=submit]').click();assert.match(await page.locator('#total').innerText(),/100\.04/);await page.locator('[data-delete]').first().click();assert.equal(await page.locator('#entries tr').count(),1);assert.match(await page.locator('#total').innerText(),/12\.20/);
await page.locator('[data-view=profile]').first().click();await page.locator('[name=salary]').fill('3000');assert.equal(await page.locator('[name=rate]').inputValue(),'14.38');assert.equal(await page.locator('[name=rate]').getAttribute('readonly'),'');assert.match(await page.locator('#total').innerText(),/8\.99/);
const downloadPromise=page.waitForEvent('download');await page.locator('#backup').click();const download=await downloadPromise;await download.saveAs('test-results/backup.json');const backup=JSON.parse(fs.readFileSync('test-results/backup.json','utf8'));assert.equal(backup.document.entries.length,1);
await page.locator('[name=salary]').fill('4000');await page.locator('#restore').setInputFiles('test-results/backup.json');await page.waitForFunction(()=>document.querySelector('#total').textContent.includes('8.99'));
await page.locator('#add').click();await page.locator('[name=mode]').selectOption('time');await page.locator('[name=start]').fill('22:00');await page.locator('[name=end]').fill('02:30');await page.locator('[name=overnight]').check();await page.locator('[name=deduction]').fill('0.5');await page.locator('textarea[name=description]').fill('Ujian kiraan Excel');await page.locator('[name=band]').selectOption('Night');await page.locator('#entry-form [type=submit]').click();assert.equal(await page.locator('#entries tr').count(),2);assert.match(await page.locator('#hours').innerText(),/4\.5/);
await page.locator('[data-delete]').last().click();assert.match(await page.locator('#total').innerText(),/8\.99/);
const conflict=await page.evaluate(async()=>{const all=await(await fetch('api.php')).json();const row=all.claims.find(x=>x.month==='2099-06');return (await fetch('api.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document:row.document,revision:0})})).status;});assert.equal(conflict,409);
await page.evaluate(()=>window.print=()=>{});await page.locator('#print').click();assert.match(await page.locator('#print-document').innerText(),/PERAKUAN KETUA JABATAN/);await page.pdf({path:'test-results/claim.pdf',preferCSSPageSize:true});
// Failed save keeps pending data, retry succeeds.
await page.route('**/api.php',async route=>{if(route.request().method()==='POST')return route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'Ujian gangguan simpanan. Cuba lagi.'})});return route.continue();});
await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#save-status').textContent==='Belum disimpan');assert.match(await page.locator('#notice').innerText(),/gangguan/);assert.equal(await page.locator('#entries tr').count(),1);await page.unroute('**/api.php');await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#save-status').textContent==='Disimpan pada komputer ini');
// History snapshots and empty new months remain separate.
await page.locator('#month').fill('2099-07');await page.locator('#month').dispatchEvent('change');assert.equal(await page.locator('#entries tr').count(),0);await page.locator('#saved-month').selectOption('2099-06');assert.equal(await page.locator('#entries tr').count(),1);
// Every primary surface at standard sizes, including mobile landscape.
for(const width of [375,768,1024,1440]){await page.setViewportSize({width,height:900});for(const section of ['records','profile','calculation']){await page.locator('[data-view='+section+']').first().click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow: '+width+' '+section);}}
await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:844,height:390});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.setViewportSize({width:390,height:844});await page.locator('[data-view=records]').first().click();await page.screenshot({path:'test-results/mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
console.log('PASS: isolated database, date/description/deduction errors, missing salary, backup/restore, conflict, failed-save/retry, monthly isolation, 375/768/1024/1440 responsive, reduced motion, Excel RM78.08, save/reload, edit, delete, salary rate, print, mobile overflow, no browser errors.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
